name: proyecto-2-planificacion
services:
  proyecto-2-planificacion:
    build: .
    env_file:
      - .env
    volumes:
      - ./extracted_temp:/app/extracted_temp
      - ./generations:/app/generations
    networks:
      - proxy_net
      
networks:
  proxy_net:
    external: true
